---
title: mon blog
timezone: UTC
collections:
  cours:
    title: Cours
    output: true
  posts:
    title: Posts
    output: true
  produits:
    title: Produits
    output: true
  uploads:
    title: Uploads
    output: true
